dist: bionic
os: linux
language: shell

services:
  - docker

env:
  global:
    - DOCKER_PLATFORMS="linux/amd64,linux/arm64,linux/ppc64le,linux/s390x,linux/386,linux/arm/v7,linux/arm/v6"

git:
  depth: 1

before_install:
  # Registering file format recognizers since RUN command is used
  - sudo docker run --privileged linuxkit/binfmt:v0.7
  # Update docker to the latest version, enable experimental mode, enable BuildKit
  - echo '{"experimental":true,"features":{"buildkit":true}}' | sudo tee /etc/docker/daemon.json
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  # Get scripts for building multi-architectural Docker images and manifests
  - id=$(docker create moikot/mua-docker-tools:master)
  - docker cp $id:/scripts.sh /tmp/mua-scripts.sh
  - docker rm -v $id

stages:
  - name: build amd64
    if: branch != master AND tag IS blank
  - name: build and deploy master
    if: branch = master AND tag IS blank
  - name: build and deploy a version
    if: tag =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/

matrix:
  include:

    - stage: build amd64
      script:
        - >-
          bash -c "/tmp/mua-scripts.sh build_images
          ${TRAVIS_REPO_SLUG} ${TRAVIS_COMMIT::6} "linux/amd64"
          ${DOCKER_USERNAME} ${DOCKER_PASSWORD}"

    - stage: build and deploy master
      script:
        - >-
          bash -c "/tmp/mua-scripts.sh build_images
          ${TRAVIS_REPO_SLUG} master ${DOCKER_PLATFORMS}
          ${DOCKER_USERNAME} ${DOCKER_PASSWORD}"

    - stage: build and deploy a version
      script:
        - >-
          bash -c "/tmp/mua-scripts.sh build_images
          ${TRAVIS_REPO_SLUG} ${TRAVIS_TAG} ${DOCKER_PLATFORMS}
          ${DOCKER_USERNAME} ${DOCKER_PASSWORD}"
        - >-
          bash -c "/tmp/mua-scripts.sh push_readme
          ${TRAVIS_REPO_SLUG} README.md
          ${DOCKER_USERNAME} ${DOCKER_PASSWORD}"

notifications:
  email: false
