sudo: required
dist: bionic

language: bash

services:
  - docker

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::6}
    - DOCKER_PLATFORMS="linux/amd64,linux/arm64,linux/ppc64le,linux/s390x,linux/386,linux/arm/v7,linux/arm/v6"

git:
  depth: 1

before_install:
  # Registering file format recognizers since RUN command is used
  - sudo docker run --privileged linuxkit/binfmt:v0.7
  # Update docker to the latest version, enable experimental mode, enable BuildKit
  - echo '{"experimental":true,"features":{"buildkit":true}}' | sudo tee /etc/docker/daemon.json
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  # Get scripts for building multi-architectural Docker images and manifests
  - id=$(docker create moikot/mua-docker-tools:master)
  - docker cp $id:/scripts.sh /tmp/mua-scripts.sh
  - docker rm -v $id

script:
  # Build Docker images
  - >-
    bash -c "/tmp/mua-scripts.sh build_images
    ${TRAVIS_REPO_SLUG} master ${DOCKER_PLATFORMS}
    ${DOCKER_USERNAME} ${DOCKER_PASSWORD}"

deploy:
  provider: script
  script: >-
    bash -c "/tmp/mua-scripts.sh build_images
    ${TRAVIS_REPO_SLUG} ${TRAVIS_TAG} ${DOCKER_PLATFORMS}
    ${DOCKER_USERNAME} ${DOCKER_PASSWORD} &&
    /tmp/mua-scripts.sh push_readme
    ${TRAVIS_REPO_SLUG} README.md
    ${DOCKER_USERNAME} ${DOCKER_PASSWORD}"
  on:
    tags: true

notifications:
  email: false
